// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Asssignment_1.board;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private int nodeA;
	/**
	 * 
	 */
	private int nodeB;
	/**
	 * 
	 */
	private int roadOwnerId;

	/**
	 * 
	 * @param id 
	 * @param roadOwnerId 
	 * @param nodeA 
	 * @param NodeB 
	 */
	public void Edge(int id, int roadOwnerId, Node nodeA, Node NodeB) {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getNodeA() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getNodeB() {
	}
}
