// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Asssignment_1.board;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private int ownerId;
	/**
	 * 
	 */
	private StructureType structureType;

	/**
	 * 
	 * @param id 
	 * @param ownerId 
	 * @param structureType 
	 */
	public void Node(int id, int ownerId, StructureType structureType) {
	}

	/**
	 * 
	 * @return 
	 */
	public StructureType getStructureType() {
	}
}
