// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package team8.catan.board;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Tile[] tiles;
	/**
	 * 
	 */
	private Node[] nodes;
	/**
	 * 
	 */
	private Edge[] edges;
	/**
	 * 
	 */
	public Tile[] tile;
	/**
	 * 
	 */
	public Edge[] edge;
	/**
	 * 
	 */
	public Node[] node;

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Tile getTile(int id) {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Node getNode(int id) {
	}

	/**
	 * 
	 * @return 
	 * @param id 
	 */
	public Edge getEdge(int id) {
	}

	/**
	 * 
	 * @param tiles 
	 * @param nodes 
	 * @param Edges 
	 */
	public void Board(Tile[] tiles, Node[] nodes, Edge[] Edges) {
	}
}
