// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package team8.catan.board;

/************************************************************/
/**
 * 
 */
public class MapPreset {
	/**
	 * 
	 * @return 
	 */
	public Board createDefaultBoard() {
	}

	/**
	 * 
	 */
	public void MapPreset() {
	}
}
