// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package team8.catan.board;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceType resourceType;
	/**
	 * 
	 */
	private int diceNumber;
	/**
	 * 
	 */
	private int[] adjacentNodeIds;

	/**
	 * 
	 * @param id 
	 * @param diceNumber 
	 * @param adjacenNodeIds 
	 * @param resourceType 
	 */
	public void Tile(int id, int diceNumber, int[] adjacenNodeIds, ResourceType resourceType) {
	}

	/**
	 * 
	 * @return 
	 */
	public ResourceType getResourceType() {
	}
}
