// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package team8.catan.gameplay;

import team8.catan.configuration.SimulationConfig;
import team8.catan.players.Player;
import team8.catan.board.Board;
import team8.catan.output.ConsoleActionLogger;
import team8.catan.rules.RuleChecker;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private int round;
	/**
	 * 
	 */
	public SimulationConfig simulationconfig;
	/**
	 * 
	 */
	public Board board;
	/**
	 * 
	 */
	public RuleChecker rulechecker;
	/**
	 * 
	 */
	public ConsoleActionLogger consoleactionlogger;
	/**
	 * 
	 */
	public Player[] player;

	/**
	 * 
	 */
	public void setup() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean shouldTerminate() {
	}

	/**
	 * 
	 */
	public void run() {
	}

	/**
	 * 
	 * @param player 
	 */
	public void executeTurn(Player player) {
	}

	/**
	 * 
	 * @param board 
	 * @param logger 
	 * @param ruleChecker 
	 * @param players 
	 * @param SimulationConfig 
	 */
	public void Game(Board board, ConsoleActionLogger logger, RuleChecker ruleChecker, Player[] players,
			SimulationConfig SimulationConfig) {
	}
}
