// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package team8.catan.rules;

import team8.catan.gameplay.Action;
import team8.catan.gameplay.Game;
import team8.catan.players.Player;
import team8.catan.board.Board;

/************************************************************/
/**
 * 
 */
public class RuleChecker {
	/**
	 * 
	 */
	public Board board;
	/**
	 * 
	 */
	public Player player;
	/**
	 * 
	 */
	public Action action;

	/**
	 * 
	 * @param action 
	 * @param game 
	 * @param player 
	 * @return 
	 */
	public boolean isLegal(Action action, Game game, Player player) {
	}

	/**
	 * 
	 */
	public void RuleChecker() {
	}
}
