// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package team8.catan.output;

import team8.catan.players.Player;

/************************************************************/
/**
 * 
 */
public class ConsoleActionLogger {
	/**
	 * 
	 * @param round 
	 * @param actionText 
	 * @param playerID 
	 */
	public void logTurn(int round, String actionText, int playerID) {
	}

	/**
	 * 
	 * @param round 
	 * @param player 
	 */
	public void logRoundVPs(int round, Player player) {
	}

	/**
	 * 
	 */
	public void ConesoleActionLogger() {
	}
}
