// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package papyrus.code.app;

import Asssignment_1.Configuration.ConfigLoader;
import Asssignment_1.Gameplay.Game;
import Asssignment_1.board.MapPreset;
import Asssignment_1.output.ConsoleActionLogger;

/************************************************************/
/**
 * 
 */
public class Demonstrator {
	/**
	 * 
	 */
	public Game game;
	/**
	 * 
	 */
	public MapPreset configloader;
	/**
	 * 
	 */
	public ConfigLoader configloader;
	/**
	 * 
	 */
	public ConsoleActionLogger consoleactionlogger;

	/**
	 * 
	 * @param args 
	 */
	public static void main(String[] args) {
	}

	/**
	 * 
	 */
	public void Demonstrator() {
	}
}
