// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package team8.catan.configuration;

/************************************************************/
/**
 * 
 */
public class ConfigLoader {
	/**
	 * 
	 * @param path 
	 * @return 
	 */
	public SimulationConfig load(String path) {
	}

	/**
	 * 
	 */
	public void ConfigLoader() {
	}
}
