// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package team8.catan.configuration;

/************************************************************/
/**
 * 
 */
public class SimulationConfig {
	/**
	 * 
	 */
	public undef maxRounds;
	/**
	 * 
	 */
	private int maxRounds;

	/**
	 * 
	 * @return 
	 */
	public boolean validate() {
	}

	/**
	 * 
	 * @param maxRounds 
	 */
	public void SimulationConfig(int maxRounds) {
	}
}
