// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Asssignment_1.Gameplay;

/************************************************************/
/**
 * 
 */
public class Action {
	/**
	 * 
	 */
	private ActionType ActionType;
	/**
	 * 
	 */
	private int targetID;

	/**
	 * 
	 * @param targetId 
	 */
	public void Action(int targetId) {
	}
}
