// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package papyrus.code.gameplay;

/************************************************************/
/**
 * 
 */
public class Action {
	/**
	 * 
	 */
	private ActionType ActionType;
	/**
	 * 
	 */
	private int targetID;

	/**
	 * 
	 * @param targetId 
	 */
	public void Action(int targetId) {
	}
}
