// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package papyrus.code.gameplay;

/************************************************************/
/**
 * 
 */
public enum GameState {
	/**
	 * 
	 */
	SETUP,
	/**
	 * 
	 */
	RUNNING,
	/**
	 * 
	 */
	TERMINATED;
}
