// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Asssignment_1.Gameplay;

/************************************************************/
/**
 * 
 */
public enum GameState {
	/**
	 * 
	 */
	SETUP,
	/**
	 * 
	 */
	RUNNING,
	/**
	 * 
	 */
	TERMINATED;
}
