// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Asssignment_1.Gameplay;

import Asssignment_1.Configuration.SimulationConfig;
import Asssignment_1.Players.Player;
import Asssignment_1.board.Board;
import Asssignment_1.output.ConsoleActionLogger;
import Asssignment_1.rules.RuleChecker;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private int round;
	/**
	 * 
	 */
	public SimulationConfig simulationconfig;
	/**
	 * 
	 */
	public Board board;
	/**
	 * 
	 */
	public RuleChecker rulechecker;
	/**
	 * 
	 */
	public ConsoleActionLogger consoleactionlogger;
	/**
	 * 
	 */
	public Player[] player;

	/**
	 * 
	 */
	public void setup() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean shouldTerminate() {
	}

	/**
	 * 
	 */
	public void run() {
	}

	/**
	 * 
	 * @param player 
	 */
	public void executeTurn(Player player) {
	}

	/**
	 * 
	 * @param board 
	 * @param logger 
	 * @param ruleChecker 
	 * @param players 
	 * @param SimulationConfig 
	 */
	public void Game(Board board, ConsoleActionLogger logger, RuleChecker ruleChecker, Player[] players,
			SimulationConfig SimulationConfig) {
	}
}
