// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Asssignment_1.rules;

import Asssignment_1.Gameplay.Action;
import Asssignment_1.Gameplay.Game;
import Asssignment_1.Players.Player;
import Asssignment_1.board.Board;

/************************************************************/
/**
 * 
 */
public class RuleChecker {
	/**
	 * 
	 */
	public Board board;
	/**
	 * 
	 */
	public Player player;
	/**
	 * 
	 */
	public Action action;

	/**
	 * 
	 * @param action 
	 * @param game 
	 * @param player 
	 * @return 
	 */
	public boolean isLegal(Action action, Game game, Player player) {
	}

	/**
	 * 
	 */
	public void RuleChecker() {
	}
}
