// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Asssignment_1.players;

import Asssignment_1.Gameplay.Action;
import Asssignment_1.Gameplay.Game;

/************************************************************/
/**
 * 
 */
public class RandomPolicy {
	/**
	 * 
	 * @param game 
	 * @param player 
	 * @return 
	 */
	public Action chooseAction(Game game, Player player) {
	}
}
