// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Asssignment_1.players;

import Asssignment_1.Gameplay.ActionType;
import Asssignment_1.board.ResourceType;

/************************************************************/
/**
 * 
 */
public class ResourceHand {
	/**
	 * 
	 */
	public int[] counts;

	/**
	 * 
	 * @return 
	 */
	public int totalCards() {
	}

	/**
	 * 
	 * @param actionType 
	 * @return 
	 */
	public boolean canAfford(ActionType actionType) {
	}

	/**
	 * 
	 * @param type 
	 * @param n 
	 */
	public void add(ResourceType type, int n) {
	}

	/**
	 * 
	 * @param actionType 
	 */
	public void spendFor(ActionType actionType) {
	}

	/**
	 * 
	 * @param counts 
	 */
	public void ResourceHand(int[] counts) {
	}
}
