// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Asssignment_1;

import Asssignment_1.board.StructureType;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	public int ownerId;
	/**
	 * 
	 */
	public StructureType structureType;

	/**
	 * 
	 */
	public void Node() {
	}
}
