// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Asssignment_1;

import Asssignment_1.board.ResourceType;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	public ResourceType resourceType;
	/**
	 * 
	 */
	public int diceNumber;
	/**
	 * 
	 */
	public int[] adjacentNodeIds;

	/**
	 * 
	 */
	public void Tile() {
	}
}
