// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package team8.catan.app;

import team8.catan.configuration.ConfigLoader;
import team8.catan.gameplay.Game;
import team8.catan.board.MapPreset;
import team8.catan.output.ConsoleActionLogger;

/************************************************************/
/**
 * 
 */
public class Demonstrator {
	/**
	 * 
	 */
	public Game game;
	/**
	 * 
	 */
	public MapPreset configloader;
	/**
	 * 
	 */
	public ConfigLoader configloader;
	/**
	 * 
	 */
	public ConsoleActionLogger consoleactionlogger;

	/**
	 * 
	 * @param args 
	 */
	public static void main(String[] args) {
	}

	/**
	 * 
	 */
	public void Demonstrator() {
	}
}
