// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package team8.catan.app;

import team8.catan.board.Board;
import team8.catan.board.MapPreset;
import team8.catan.configuration.SimulationConfig;
import team8.catan.gameplay.Game;
import team8.catan.output.ConsoleActionLogger;
import team8.catan.players.Player;
import team8.catan.players.RandomPolicy;
import team8.catan.players.ResourceHand;
import team8.catan.rules.RuleChecker;

/************************************************************/
/**
 * Main entry point for the Catan simulator demonstration.
 * This class sets up and runs a complete game simulation to showcase
 * the functionality of the simulator.
 * 
 * Key mechanisms demonstrated:
 * 1. Board creation using MapPreset factory
 * 2. Player initialization with AI policies
 * 3. Game loop execution with turn-based play
 * 4. Action logging to track game progress
 * 5. Rule validation for player actions
 */
public class Demonstrator {

	/**
	 * Main method - entry point for the simulator demonstration.
	 * 
	 * This demonstrates the complete flow of a Catan game simulation:
	 * - Creates the game board
	 * - Initializes players with starting resources and AI policies
	 * - Configures the simulation parameters
	 * - Runs the game and outputs results
	 * 
	 * @param args Command line arguments (not used)
	 */
	public static void main(String[] args) {
		System.out.println("===== Catan Simulator Demo =====");
		System.out.println();
		
		// Step 1: Create the game board
		// The MapPreset factory creates a board with the standard Catan layout.
		// For this initial version, we use a simplified board to focus on
		// demonstrating the game mechanics and turn flow.
		System.out.println("Setting up game board...");
		MapPreset preset = new MapPreset();
		Board board = preset.createDefaultBoard();
		
		// Step 2: Configure the simulation
		// The SimulationConfig controls how many rounds the game will run.
		// We set it to 10 rounds for a quick demonstration.
		System.out.println("Configuring simulation (10 rounds)...");
		SimulationConfig config = new SimulationConfig(10);
		
		// Step 3: Initialize players
		// Each player needs:
		// - A unique ID for identification
		// - Victory points (starting at 0)
		// - A resource hand (currently empty for simplicity)
		// - An AI policy that determines their strategy
		// 
		// We create 3 players, each using the RandomPolicy.
		// The RandomPolicy implements requirement R1.8: it performs a simple
		// linear check of all available actions and picks one randomly.
		System.out.println("Creating players with RandomPolicy AI...");
		Player[] players = new Player[] {
			new Player(1, 0, new ResourceHand(new int[6]), new RandomPolicy()),
			new Player(2, 0, new ResourceHand(new int[6]), new RandomPolicy()),
			new Player(3, 0, new ResourceHand(new int[6]), new RandomPolicy())
		};
		
		// Step 4: Set up the action logger
		// The ConsoleActionLogger outputs each action to the console,
		// allowing us to observe the game as it progresses.
		ConsoleActionLogger logger = new ConsoleActionLogger();
		
		// Step 5: Create the rule checker
		// The RuleChecker validates actions to ensure they follow game rules.
		// This implements requirement R1.6: maintaining game invariants.
		// It checks things like whether a player has enough resources.
		RuleChecker ruleChecker = new RuleChecker();
		
		// Step 6: Create and configure the game
		// The Game object ties everything together: board, players,
		// configuration, logger, and rule checker.
		System.out.println("Initializing game...");
		Game game = new Game(board, logger, ruleChecker, players, config);
		
		// Step 7: Run the simulation
		// The game loop will execute until:
		// - The maximum number of rounds is reached, OR
		// - A safety timeout occurs (to prevent infinite loops)
		// 
		// During each round, every player takes a turn:
		// 1. The player's AI policy chooses an action
		// 2. The rule checker validates the action
		// 3. If legal, the action is logged
		System.out.println();
		System.out.println("Starting simulation...");
		System.out.println();
		game.run();
		
		// Step 8: Simulation complete
		System.out.println();
		System.out.println("===== Simulation Complete =====");
		System.out.println("Final round: " + game.getRound());
	}
}
