// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package team8.catan.players;

import team8.catan.gameplay.Action;
import team8.catan.gameplay.Game;

/************************************************************/
/**
 * 
 */
public interface AgentPolicy {
	/**
	 * 
	 * @param game 
	 * @param player 
	 * @return 
	 */
	public Action chooseAction(Game game, Player player);
}
