// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package team8.catan.players;

import team8.catan.gameplay.Action;
import team8.catan.gameplay.Game;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	public int vp;
	/**
	 * 
	 */
	public ResourceHand resourcehand;
	/**
	 * 
	 */
	public AgentPolicy agentpolicy;

	/**
	 * 
	 * @param game 
	 * @return 
	 */
	public Action chooseAction(Game game) {
	}

	/**
	 * 
	 * @param id 
	 * @param vp 
	 * @param ResourceHand 
	 * @param AgentPolicy 
	 */
	public void Player(int id, int vp, ResourceHand ResourceHand, AgentPolicy AgentPolicy) {
	}

	/**
	 * 
	 */
	public void setID() {
	}
}
